name: veto_app
description: "Veto - Коллективное принятие решений с диктаторским подходом"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.4.0    # Официальный клиент Supabase
  flutter_riverpod: ^2.5.1    # State Management
  riverpod_annotation: ^2.3.5 # Генерация кода для Riverpod
  go_router: ^13.2.0          # Мощный роутинг
  google_fonts: ^6.2.1        # Для брутальной типографики

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8        # Генератор кода
  riverpod_generator: ^2.4.0  # Генератор для Riverpod

flutter:
  uses-material-design: true
